import { Fragment, type ReactNode } from "react";

/**
 * Renders the small markdown subset the documents use: headings, bullets,
 * block quotes, horizontal rules, bold and italic.
 *
 * Written by hand rather than pulled from a library because the input is
 * generated by our own code and the subset is fixed. Nothing here builds HTML
 * from a string, so document text cannot inject markup.
 */

function inline(text: string, key: string): ReactNode[] {
  const nodes: ReactNode[] = [];
  const pattern = /(\*\*[^*]+\*\*|\*[^*]+\*)/g;
  let last = 0;
  let match: RegExpExecArray | null;
  let index = 0;

  while ((match = pattern.exec(text)) !== null) {
    if (match.index > last) nodes.push(text.slice(last, match.index));
    const token = match[0];
    if (token.startsWith("**")) {
      nodes.push(<strong key={`${key}-b${index}`}>{token.slice(2, -2)}</strong>);
    } else {
      nodes.push(<em key={`${key}-i${index}`}>{token.slice(1, -1)}</em>);
    }
    last = match.index + token.length;
    index += 1;
  }
  if (last < text.length) nodes.push(text.slice(last));
  return nodes.length > 0 ? nodes : [text];
}

export function Markdown({ source }: { source: string }) {
  const blocks: ReactNode[] = [];
  const lines = source.split("\n");
  let bullets: string[] = [];
  let paragraph: string[] = [];

  const flushBullets = (key: string) => {
    if (bullets.length === 0) return;
    blocks.push(
      <ul key={`ul-${key}`}>
        {bullets.map((item, index) => (
          <li key={index}>{inline(item, `${key}-${index}`)}</li>
        ))}
      </ul>,
    );
    bullets = [];
  };

  const flushParagraph = (key: string) => {
    if (paragraph.length === 0) return;
    blocks.push(<p key={`p-${key}`}>{inline(paragraph.join(" "), key)}</p>);
    paragraph = [];
  };

  lines.forEach((raw, index) => {
    const line = raw.trim();
    const key = String(index);

    if (!line) {
      flushBullets(key);
      flushParagraph(key);
      return;
    }
    if (line === "---") {
      flushBullets(key);
      flushParagraph(key);
      blocks.push(<hr key={`hr-${key}`} />);
      return;
    }
    if (line.startsWith("## ")) {
      flushBullets(key);
      flushParagraph(key);
      blocks.push(<h2 key={key}>{line.slice(3)}</h2>);
      return;
    }
    if (line.startsWith("# ")) {
      flushBullets(key);
      flushParagraph(key);
      blocks.push(<h1 key={key}>{line.slice(2)}</h1>);
      return;
    }
    if (line.startsWith("> ")) {
      flushBullets(key);
      flushParagraph(key);
      blocks.push(
        <blockquote key={key}>{inline(line.slice(2), key)}</blockquote>,
      );
      return;
    }
    if (line.startsWith("- ")) {
      flushParagraph(key);
      bullets.push(line.slice(2));
      return;
    }
    flushBullets(key);
    paragraph.push(line);
  });

  flushBullets("end");
  flushParagraph("end");

  return <div className="doc-view">{blocks.map((block, i) => (
    <Fragment key={i}>{block}</Fragment>
  ))}</div>;
}
